name: 'Validate Helm Charts'

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'my-service/**'
  push:
    branches: [ main ]
    paths:
      - 'my-service/**'

jobs:
  validate-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Helm Chart
        uses: BoldFellow/helm-validate-action@main
        with:
          chart-path: './my-service/charts'
          values-file: './my-service/charts/values.yaml'